//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOnline.FFXI.Utils.DataBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayOnline.FFXI.Utils.DataBrowser.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains ability information....
        /// </summary>
        internal static string AbilityCheck {
            get {
                return ResourceManager.GetString("AbilityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ability information - please wait....
        /// </summary>
        internal static string AbilityLoad {
            get {
                return ResourceManager.GetString("AbilityLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ability information ({0}/{1}) - please wait....
        /// </summary>
        internal static string AbilityLoadProgress {
            get {
                return ResourceManager.GetString("AbilityLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string ColumnHeader_Index {
            get {
                return ResourceManager.GetString("ColumnHeader:Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where the images should be saved.
        ///WARNING: Existing files with the same name will be overwritten without prompting..
        /// </summary>
        internal static string Description_BrowseImageExportFolder {
            get {
                return ResourceManager.GetString("Description:BrowseImageExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file contents to XML.
        ///This may take quite a while..
        /// </summary>
        internal static string Dialog_ExportFileContents {
            get {
                return ResourceManager.GetString("Dialog:ExportFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving all images to disk.
        ///This may take quite a while..
        /// </summary>
        internal static string Dialog_SaveAllImages {
            get {
                return ResourceManager.GetString("Dialog:SaveAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains dialog strings....
        /// </summary>
        internal static string DialogCheck {
            get {
                return ResourceManager.GetString("DialogCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dialog strings - please wait....
        /// </summary>
        internal static string DialogLoad {
            get {
                return ResourceManager.GetString("DialogLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dialog strings ({0}/{1}) - please wait....
        /// </summary>
        internal static string DialogLoadProgress {
            get {
                return ResourceManager.GetString("DialogLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string E_Test_Contains {
            get {
                return ResourceManager.GetString("E:Test.Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t contain.
        /// </summary>
        internal static string E_Test_DoesntContain {
            get {
                return ResourceManager.GetString("E:Test.DoesntContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t match regexp.
        /// </summary>
        internal static string E_Test_DoesntMatchRegexp {
            get {
                return ResourceManager.GetString("E:Test.DoesntMatchRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string E_Test_EndsWith {
            get {
                return ResourceManager.GetString("E:Test.EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exactly matches.
        /// </summary>
        internal static string E_Test_Equals {
            get {
                return ResourceManager.GetString("E:Test.Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches regexp.
        /// </summary>
        internal static string E_Test_MatchesRegexp {
            get {
                return ResourceManager.GetString("E:Test.MatchesRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string E_Test_StartsWith {
            get {
                return ResourceManager.GetString("E:Test.StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where the exported item data will be placed.  The file name will be based on the data language and type, and will include a timestamp..
        /// </summary>
        internal static string Export_DirDialogDesc {
            get {
                return ResourceManager.GetString("Export:DirDialogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Fantasy XI.
        /// </summary>
        internal static string FFXI1 {
            get {
                return ResourceManager.GetString("FFXI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise of the Zilart.
        /// </summary>
        internal static string FFXI2 {
            get {
                return ResourceManager.GetString("FFXI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains of Promathia.
        /// </summary>
        internal static string FFXI3 {
            get {
                return ResourceManager.GetString("FFXI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasures of Aht Urhgan.
        /// </summary>
        internal static string FFXI4 {
            get {
                return ResourceManager.GetString("FFXI4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings of the Goddess.
        /// </summary>
        internal static string FFXI5 {
            get {
                return ResourceManager.GetString("FFXI5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Crystalline Prophecy.
        /// </summary>
        internal static string FFXI6 {
            get {
                return ResourceManager.GetString("FFXI6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Moogle Kupo d&apos;Etat.
        /// </summary>
        internal static string FFXI7 {
            get {
                return ResourceManager.GetString("FFXI7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Shantotto Ascension.
        /// </summary>
        internal static string FFXI8 {
            get {
                return ResourceManager.GetString("FFXI8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seekers of Adoulin.
        /// </summary>
        internal static string FFXI9 {
            get {
                return ResourceManager.GetString("FFXI9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning file for images - please wait....
        /// </summary>
        internal static string ImageScan {
            get {
                return ResourceManager.GetString("ImageScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning file for images ({0} found so far) - please wait....
        /// </summary>
        internal static string ImageScanProgress {
            get {
                return ResourceManager.GetString("ImageScanProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;invalid entry&gt;.
        /// </summary>
        internal static string InvalidEntry {
            get {
                return ResourceManager.GetString("InvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains item data....
        /// </summary>
        internal static string ItemCheck {
            get {
                return ResourceManager.GetString("ItemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Field.
        /// </summary>
        internal static string ItemField_Any {
            get {
                return ResourceManager.GetString("ItemField:Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading item information - please wait....
        /// </summary>
        internal static string ItemLoad {
            get {
                return ResourceManager.GetString("ItemLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading item information ({0}/{1}) - please wait....
        /// </summary>
        internal static string ItemLoadProgress {
            get {
                return ResourceManager.GetString("ItemLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abilities.
        /// </summary>
        internal static string Menu_Abilities {
            get {
                return ResourceManager.GetString("Menu:Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ability Descriptions.
        /// </summary>
        internal static string Menu_AbilityDescriptions {
            get {
                return ResourceManager.GetString("Menu:AbilityDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ability Names.
        /// </summary>
        internal static string Menu_AbilityNames {
            get {
                return ResourceManager.GetString("Menu:AbilityNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abyssea.
        /// </summary>
        internal static string Menu_Abyssea {
            get {
                return ResourceManager.GetString("Menu:Abyssea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualization Team.
        /// </summary>
        internal static string Menu_Actualization {
            get {
                return ResourceManager.GetString("Menu:Actualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjunct.
        /// </summary>
        internal static string Menu_Adjunct {
            get {
                return ResourceManager.GetString("Menu:Adjunct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appropriation Team.
        /// </summary>
        internal static string Menu_Appropriation {
            get {
                return ResourceManager.GetString("Menu:Appropriation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic Depopulation Team.
        /// </summary>
        internal static string Menu_AquaticDepopulation {
            get {
                return ResourceManager.GetString("Menu:AquaticDepopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Area Names.
        /// </summary>
        internal static string Menu_AreaNames {
            get {
                return ResourceManager.GetString("Menu:AreaNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Area Names (Alternate).
        /// </summary>
        internal static string Menu_AreaNamesAlt {
            get {
                return ResourceManager.GetString("Menu:AreaNamesAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Area Names (Search).
        /// </summary>
        internal static string Menu_AreaNamesShort {
            get {
                return ResourceManager.GetString("Menu:AreaNamesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string Menu_Armor {
            get {
                return ResourceManager.GetString("Menu:Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string Menu_Assistant {
            get {
                return ResourceManager.GetString("Menu:Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Researcher.
        /// </summary>
        internal static string Menu_AssociateResearcher {
            get {
                return ResourceManager.GetString("Menu:AssociateResearcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battalia Adjunct.
        /// </summary>
        internal static string Menu_BAdjunct {
            get {
                return ResourceManager.GetString("Menu:BAdjunct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battalia Assistant.
        /// </summary>
        internal static string Menu_BAssistant {
            get {
                return ResourceManager.GetString("Menu:BAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battalia Instructor.
        /// </summary>
        internal static string Menu_BInstructor {
            get {
                return ResourceManager.GetString("Menu:BInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Blue Magic Help Text.
        /// </summary>
        internal static string Menu_BlueMagicHelp {
            get {
                return ResourceManager.GetString("Menu:BlueMagicHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Character Selection.
        /// </summary>
        internal static string Menu_CharacterSelect {
            get {
                return ResourceManager.GetString("Menu:CharacterSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Chat Filter Types.
        /// </summary>
        internal static string Menu_ChatFilterTypes {
            get {
                return ResourceManager.GetString("Menu:ChatFilterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Common.
        /// </summary>
        internal static string Menu_Common {
            get {
                return ResourceManager.GetString("Menu:Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Currency.
        /// </summary>
        internal static string Menu_Currency {
            get {
                return ResourceManager.GetString("Menu:Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Day Names.
        /// </summary>
        internal static string Menu_DayNames {
            get {
                return ResourceManager.GetString("Menu:DayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dialog Tables.
        /// </summary>
        internal static string Menu_DialogTables {
            get {
                return ResourceManager.GetString("Menu:DialogTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Directions.
        /// </summary>
        internal static string Menu_Directions {
            get {
                return ResourceManager.GetString("Menu:Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dynamis.
        /// </summary>
        internal static string Menu_Dynamis {
            get {
                return ResourceManager.GetString("Menu:Dynamis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Emote Messages.
        /// </summary>
        internal static string Menu_EmoteMessages {
            get {
                return ResourceManager.GetString("Menu:EmoteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;English.
        /// </summary>
        internal static string Menu_English {
            get {
                return ResourceManager.GetString("Menu:English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Equipment Locations.
        /// </summary>
        internal static string Menu_EquipmentLocations {
            get {
                return ResourceManager.GetString("Menu:EquipmentLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Error Messages.
        /// </summary>
        internal static string Menu_ErrorMessages {
            get {
                return ResourceManager.GetString("Menu:ErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fonts &amp;&amp; Menus.
        /// </summary>
        internal static string Menu_FontsAndMenus {
            get {
                return ResourceManager.GetString("Menu:FontsAndMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;French.
        /// </summary>
        internal static string Menu_French {
            get {
                return ResourceManager.GetString("Menu:French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full.
        /// </summary>
        internal static string Menu_Full {
            get {
                return ResourceManager.GetString("Menu:Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;General Items.
        /// </summary>
        internal static string Menu_GeneralItems {
            get {
                return ResourceManager.GetString("Menu:GeneralItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;German.
        /// </summary>
        internal static string Menu_German {
            get {
                return ResourceManager.GetString("Menu:German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight: .
        /// </summary>
        internal static string Menu_Highlight {
            get {
                return ResourceManager.GetString("Menu:Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Images.
        /// </summary>
        internal static string Menu_Images {
            get {
                return ResourceManager.GetString("Menu:Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;In-Game Messages (1).
        /// </summary>
        internal static string Menu_InGameMessages1 {
            get {
                return ResourceManager.GetString("Menu:InGameMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;In-Game Messages (2).
        /// </summary>
        internal static string Menu_InGameMessages2 {
            get {
                return ResourceManager.GetString("Menu:InGameMessages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instincts.
        /// </summary>
        internal static string Menu_Instincts {
            get {
                return ResourceManager.GetString("Menu:Instincts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string Menu_Instructor {
            get {
                return ResourceManager.GetString("Menu:Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&amp;tem Data.
        /// </summary>
        internal static string Menu_ItemData {
            get {
                return ResourceManager.GetString("Menu:ItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Japanese.
        /// </summary>
        internal static string Menu_Japanese {
            get {
                return ResourceManager.GetString("Menu:Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Job Names.
        /// </summary>
        internal static string Menu_JobNames {
            get {
                return ResourceManager.GetString("Menu:JobNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Job Names (Short).
        /// </summary>
        internal static string Menu_JobNamesShort {
            get {
                return ResourceManager.GetString("Menu:JobNamesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Items.
        /// </summary>
        internal static string Menu_KeyItems {
            get {
                return ResourceManager.GetString("Menu:KeyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidation Team.
        /// </summary>
        internal static string Menu_Liquidation {
            get {
                return ResourceManager.GetString("Menu:Liquidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map &amp;.
        /// </summary>
        internal static string Menu_MapN {
            get {
                return ResourceManager.GetString("Menu:MapN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Maps.
        /// </summary>
        internal static string Menu_Maps {
            get {
                return ResourceManager.GetString("Menu:Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialization Team.
        /// </summary>
        internal static string Menu_Materialization {
            get {
                return ResourceManager.GetString("Menu:Materialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeble Burrows.
        /// </summary>
        internal static string Menu_MeebleBurrows {
            get {
                return ResourceManager.GetString("Menu:MeebleBurrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Menu Item Descriptions.
        /// </summary>
        internal static string Menu_MenuItemDesc {
            get {
                return ResourceManager.GetString("Menu:MenuItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Menu Item Text.
        /// </summary>
        internal static string Menu_MenuItemText {
            get {
                return ResourceManager.GetString("Menu:MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Merit Point Help Text.
        /// </summary>
        internal static string Menu_MeripoHelp {
            get {
                return ResourceManager.GetString("Menu:MeripoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        internal static string Menu_Missions {
            get {
                return ResourceManager.GetString("Menu:Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moblin Maze Mongers.
        /// </summary>
        internal static string Menu_MoblinMaze {
            get {
                return ResourceManager.GetString("Menu:MoblinMaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;NPC/Monster Lists.
        /// </summary>
        internal static string Menu_MobLists {
            get {
                return ResourceManager.GetString("Menu:MobLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monipulator.
        /// </summary>
        internal static string Menu_Monipulator {
            get {
                return ResourceManager.GetString("Menu:Monipulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Monster Skill Names.
        /// </summary>
        internal static string Menu_MonsterSkillNames {
            get {
                return ResourceManager.GetString("Menu:MonsterSkillNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Moon Phases.
        /// </summary>
        internal static string Menu_MoonPhases {
            get {
                return ResourceManager.GetString("Menu:MoonPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;North Half.
        /// </summary>
        internal static string Menu_NorthHalf {
            get {
                return ResourceManager.GetString("Menu:NorthHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Other.
        /// </summary>
        internal static string Menu_Other {
            get {
                return ResourceManager.GetString("Menu:Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;POL Messages.
        /// </summary>
        internal static string Menu_POLMessages {
            get {
                return ResourceManager.GetString("Menu:POLMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppet Items.
        /// </summary>
        internal static string Menu_PuppetItems {
            get {
                return ResourceManager.GetString("Menu:PuppetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string Menu_Quests {
            get {
                return ResourceManager.GetString("Menu:Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Race Names.
        /// </summary>
        internal static string Menu_RaceNames {
            get {
                return ResourceManager.GetString("Menu:RaceNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rank (Bastok).
        /// </summary>
        internal static string Menu_RankBastok {
            get {
                return ResourceManager.GetString("Menu:RankBastok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rank (San d&apos;Oria).
        /// </summary>
        internal static string Menu_RankSandOria {
            get {
                return ResourceManager.GetString("Menu:RankSandOria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rank (Windurst).
        /// </summary>
        internal static string Menu_RankWindurst {
            get {
                return ResourceManager.GetString("Menu:RankWindurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Region Names.
        /// </summary>
        internal static string Menu_RegionNames {
            get {
                return ResourceManager.GetString("Menu:RegionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        internal static string Menu_Researcher {
            get {
                return ResourceManager.GetString("Menu:Researcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revitalization Team.
        /// </summary>
        internal static string Menu_Revitalization {
            get {
                return ResourceManager.GetString("Menu:Revitalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitization Team Alpha.
        /// </summary>
        internal static string Menu_SanitizationAlpha {
            get {
                return ResourceManager.GetString("Menu:SanitizationAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitization Team Beta.
        /// </summary>
        internal static string Menu_SanitizationBeta {
            get {
                return ResourceManager.GetString("Menu:SanitizationBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitization Team Gamma.
        /// </summary>
        internal static string Menu_SanitizationGamma {
            get {
                return ResourceManager.GetString("Menu:SanitizationGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;South Half.
        /// </summary>
        internal static string Menu_SouthHalf {
            get {
                return ResourceManager.GetString("Menu:SouthHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Spell Descriptions.
        /// </summary>
        internal static string Menu_SpellDescriptions {
            get {
                return ResourceManager.GetString("Menu:SpellDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Spell Names.
        /// </summary>
        internal static string Menu_SpellNames {
            get {
                return ResourceManager.GetString("Menu:SpellNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Spells.
        /// </summary>
        internal static string Menu_Spells {
            get {
                return ResourceManager.GetString("Menu:Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Statuses.
        /// </summary>
        internal static string Menu_StatusInfo {
            get {
                return ResourceManager.GetString("Menu:StatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Names.
        /// </summary>
        internal static string Menu_StatusNames {
            get {
                return ResourceManager.GetString("Menu:StatusNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;String Tables.
        /// </summary>
        internal static string Menu_StringTables {
            get {
                return ResourceManager.GetString("Menu:StringTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style &amp;.
        /// </summary>
        internal static string Menu_StyleN {
            get {
                return ResourceManager.GetString("Menu:StyleN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;System Messages.
        /// </summary>
        internal static string Menu_SystemMessages {
            get {
                return ResourceManager.GetString("Menu:SystemMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Time-Related Terms + Pronouns.
        /// </summary>
        internal static string Menu_TimeAndPronouns {
            get {
                return ResourceManager.GetString("Menu:TimeAndPronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Titles.
        /// </summary>
        internal static string Menu_Titles {
            get {
                return ResourceManager.GetString("Menu:Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Transport Routes.
        /// </summary>
        internal static string Menu_TransportRoutes {
            get {
                return ResourceManager.GetString("Menu:TransportRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;UI Windows.
        /// </summary>
        internal static string Menu_UIWindows {
            get {
                return ResourceManager.GetString("Menu:UIWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Usable Items.
        /// </summary>
        internal static string Menu_UsableItems {
            get {
                return ResourceManager.GetString("Menu:UsableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Various (1).
        /// </summary>
        internal static string Menu_Various1 {
            get {
                return ResourceManager.GetString("Menu:Various1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Various (2).
        /// </summary>
        internal static string Menu_Various2 {
            get {
                return ResourceManager.GetString("Menu:Various2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vouchers and Slips.
        /// </summary>
        internal static string Menu_VouchersAndSlips {
            get {
                return ResourceManager.GetString("Menu:VouchersAndSlips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string Menu_Weapons {
            get {
                return ResourceManager.GetString("Menu:Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Weather Types.
        /// </summary>
        internal static string Menu_WeatherTypes {
            get {
                return ResourceManager.GetString("Menu:WeatherTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (With Pirates).
        /// </summary>
        internal static string Menu_WithPirates {
            get {
                return ResourceManager.GetString("Menu:WithPirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query component #{0} is not valid: {1}
        ///Correct the problem and try again..
        /// </summary>
        internal static string Message_InvalidQuery {
            get {
                return ResourceManager.GetString("Message:InvalidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or unhandled query type..
        /// </summary>
        internal static string Query_BadQueryType {
            get {
                return ResourceManager.GetString("Query:BadQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression..
        /// </summary>
        internal static string Query_BadRegexp {
            get {
                return ResourceManager.GetString("Query:BadRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run this test using an empty string..
        /// </summary>
        internal static string Query_NoEmptyString {
            get {
                return ResourceManager.GetString("Query:NoEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (valid) query method selected..
        /// </summary>
        internal static string Query_NoQueryType {
            get {
                return ResourceManager.GetString("Query:NoQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains quest/mission/key item information....
        /// </summary>
        internal static string QuestCheck {
            get {
                return ResourceManager.GetString("QuestCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading quest/mission/key item information - please wait....
        /// </summary>
        internal static string QuestLoad {
            get {
                return ResourceManager.GetString("QuestLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading quest/mission/key item information (section &apos;{0}&apos;, entry {1} of {2}) - please wait....
        /// </summary>
        internal static string QuestLoadProgress {
            get {
                return ResourceManager.GetString("QuestLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains spell information....
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading spell information - please wait....
        /// </summary>
        internal static string SpellLoad {
            get {
                return ResourceManager.GetString("SpellLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading spell information ({0}/{1}) - please wait....
        /// </summary>
        internal static string SpellLoadProgress {
            get {
                return ResourceManager.GetString("SpellLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching... ({0} match(es) found so far).
        /// </summary>
        internal static string Status_ItemSearch {
            get {
                return ResourceManager.GetString("Status:ItemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} matching item(s) (out of {1}).
        /// </summary>
        internal static string Status_ItemSearchDone {
            get {
                return ResourceManager.GetString("Status:ItemSearchDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains status information....
        /// </summary>
        internal static string StatusCheck {
            get {
                return ResourceManager.GetString("StatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading status information - please wait....
        /// </summary>
        internal static string StatusLoad {
            get {
                return ResourceManager.GetString("StatusLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading status information ({0}/{1}) - please wait....
        /// </summary>
        internal static string StatusLoadProgress {
            get {
                return ResourceManager.GetString("StatusLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the file contains a string table....
        /// </summary>
        internal static string StringCheck {
            get {
                return ResourceManager.GetString("StringCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading string table entries - please wait....
        /// </summary>
        internal static string StringLoad {
            get {
                return ResourceManager.GetString("StringLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading string table entries ({0}/{1}) - please wait....
        /// </summary>
        internal static string StringLoadProgress {
            get {
                return ResourceManager.GetString("StringLoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Query.
        /// </summary>
        internal static string Title_InvalidQuery {
            get {
                return ResourceManager.GetString("Title:InvalidQuery", resourceCulture);
            }
        }
    }
}
